# Generated by Django 2.2.14 on 2022-09-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('subtitle', models.CharField(max_length=10)),
                ('isbn', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=10)),
            ],
        ),
    ]
